ToDo/ToDo/Areas/Zadania/Controllers/ZadanieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDo.Areas.Zadania.Models;
using ToDo.Areas.Zadania.ViewModel;
using ToDo.Services.Export;
using ToDo.Services.Zadania;
using ToDo.Services.Zadania.SearchBar;

namespace ToDo.Areas.Zadania.Controllers
{
    public class ZadanieController : Controller
    {
        private IZadanieService Service { get; set; }

        public ZadanieController(IZadanieService service)
        {
            Service = service;
            
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            
            TasksViewConfigModel ModelView = new TasksViewConfigModel()
            {
                SortList = SessionElement<SortList>(),
                ViewConfig = SessionElement<ViewConfig>()
            };

            ModelView.PrepareForException(filterContext);

            filterContext.Result = View("Index", ModelView);
            filterContext.ExceptionHandled = true;
        }

        // GET: Zadania/Zadanie
        public ActionResult Index()
        {
            SessionElement<ViewConfig>().ClearVisibleModal();


            TasksViewConfigModel ModelView = GetStandardModelState();

            ModelView.PrepareForIndex();
            return View(ModelView);
        }

        public ActionResult Exit()
        {
            return View();
        }

        public ActionResult List()
        {
            SessionElement<ViewConfig>().SetView(Services.Zadania.ViewType.LIST);
            TasksViewConfigModel ModelView = GetStandardModelState();
            return RedirectToAction("Index");
        }

        public ActionResult Tails()
        {
            SessionElement<ViewConfig>().SetView(Services.Zadania.ViewType.TAIL);
            SessionElement<SortList>().SetTailView();

            TasksViewConfigModel ModelView = GetStandardModelState();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Task task, HttpPostedFileBase File)
        {
            SessionElement<ViewConfig>().SetVisibleModal("Add");

            if (ModelState.IsValid)
            {
                if (Service.Add(task, File))
                {
                    SessionElement<ViewConfig>().ClearVisibleModal();
                    SessionElement<SortList>().Sort(SortFilter.NULL);

                    return RedirectToAction("Index");
                }
                else return HttpNotFound("Błąd: " + Service.GetError());
            }


            TasksViewConfigModel ModelView = GetStandardModelState();

            ModelView.PrepareForIndex();

            return View("Index", ModelView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Task task, HttpPostedFileBase File)
        {
            SessionElement<ViewConfig>().SetVisibleModal("Edit");

            if (ModelState.IsValid)
            {
                if (Service.Edit(task, File))
                {
                    SessionElement<ViewConfig>().ClearVisibleModal();
                    SessionElement<SortList>().Update(Service.GetTasks(), task);

                    return RedirectToAction("Index");
                }
                else return HttpNotFound("Błąd: " + Service.GetError());
            }

            TasksViewConfigModel ModelView = GetStandardModelState();
            ModelView.PrepareForIndex();

            return View("Index", ModelView);
        }

        [HttpGet]
        public ActionResult Image(int id)
        {
            Task t = SessionElement<SortList>().GetTask(id);

            return (t == null)
                ? null
                : File(t.ImageContent, t.FileType);
        }
        public ActionResult Delete(int id)
        {
            if (!Service.Remove(id))
                HttpNotFound("Błąd: " + Service.GetError());

            SessionElement<SortList>().Sort(SortFilter.NULL);
            return RedirectToAction("Index");
        }

        public ActionResult Description(int id)
        {
            TasksViewConfigModel ModelView = GetStandardModelState();

            ModelView.PrepareForDescription(id);

            return View("Index", ModelView);
        }

        public ActionResult Edit(int id)
        {
            TasksViewConfigModel ModelView = GetStandardModelState();
            ModelView.PrepareForEdit(id);

            return View("Index", ModelView);
        }

        public ActionResult SortByTopic()
        {
            SessionElement<SortList>().Sort(SortFilter.TOPIC);
            return RedirectToAction("Index");
        }

        public ActionResult SortByEnd()
        {
            SessionElement<SortList>().Sort(SortFilter.END);
            return RedirectToAction("Index");
        }

        public ActionResult SortByPriority()
        {
            SessionElement<SortList>().Sort(SortFilter.PRIORITY);
            return RedirectToAction("Index");
        }

        public ActionResult SortByStart()
        {
            SessionElement<SortList>().Sort(SortFilter.START);
            return RedirectToAction("Index");
        }

        public ActionResult SortByStatus()
        {
            SessionElement<SortList>().Sort(SortFilter.STATUS);
            return RedirectToAction("Index");
        }

        public ActionResult SwapPrevious(int id)
        {
            SessionElement<SortList>().SwapPrevious(id);
            return RedirectToAction("Index");
        }

        public ActionResult SwapNext(int id)
        {
            SessionElement<SortList>().SwapNext(id);
            return RedirectToAction("Index");
        }

        public ActionResult ChangeTasksPerSite(int id)
        {

            SessionElement<ViewConfig>().MultiplierTaskPerSite = id;
            return RedirectToAction("Index");
        }

        public ActionResult ChangeActualSite(int id)
        {

            SessionElement<ViewConfig>().ActualSite = id;
            return RedirectToAction("Index");
        }


        [HttpPost]
        public ActionResult Search(Content content)
        {
            SessionElement<SortList>().SearchBar = content;
            SessionElement<SortList>().HandleSearchBar = true;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Export(string ExportType, string OneSite)
        {
            ExportResponse respo;
            if (Request.HttpMethod == "POST")
            {
                bool onlyOneSite;
                try
                {
                    onlyOneSite = OneSite.Equals("on");
                }
                catch (NullReferenceException)
                {
                    onlyOneSite = false;
                }

                int actualPage = SessionElement<ViewConfig>().ActualSite;
                int perSite = SessionElement<ViewConfig>().TaskPerSite;

                IEnumerable<Task> list = onlyOneSite
                    ? SessionElement<SortList>().GetSectionFromList(actualPage, perSite)
                    : SessionElement<SortList>().GetWholeList();
                
                if (list == null)
                {
                    throw new Exception("Nie można eksportować pustej listy.");
                }
                Dictionary<string, IExport> exporters = new Dictionary<string, IExport> {
                    { "TXT", new ExportTxt(Response, list) },
                    { "XLS", new ExportXls(Response, list) },
                    { "PDF", new ExportPdf(Response, list) }
                };

                IExport exporter = exporters[ExportType];

                exporter.PrepareData(onlyOneSite);

                exporter.Export();

                if (ExportType.Equals("PDF"))
                    respo = new ExportResponse($"{exporter.GetName}.{exporter.Extension}", exporter.ContentType, (exporter as ExportPdf)._memory);
            }

            respo = new ExportResponse("Index");

            if (respo.Type == ExportResponseType.FILE)
                return File(respo.FileArray, respo.ContentType, respo.Name);
            
            return RedirectToAction(respo.Redirect);
        }

        private T SessionElement<T>() where T : class, new() {
            Dictionary<Type, string> names = new Dictionary<Type, string>
            {
                { typeof(ViewConfig), "ViewConfig" },
                { typeof(SortList), "SortList" }
            };

            if (!names.ContainsKey(typeof(T)))
                throw new Exception("Sesja nie obsługuje obiektu tego typu.");

            string name = names[typeof(T)];

            T result =((Session[name] as T == null)
                ? Session[name] = new T()
                : Session[name]
            ) as T;

            if (typeof(T) == typeof(SortList))
                (result as SortList).TryUpdate(Service.GetTasks());

            return result;
        }

        private TasksViewConfigModel GetStandardModelState()
        {
            return new TasksViewConfigModel()
            {
                SortList = SessionElement<SortList>(),
                ViewConfig = SessionElement<ViewConfig>()
            };
        }
    }
}

ToDo/ToDo/Areas/Zadania/Views/Zadanie/Exit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <script type="text/javascript">
        window.close();
    </script>
    <p>
        Jestem pełen podziwu. Ten skrypt jest obsługiwany tylko przez Microsoft Edge. Jeżeli widzisz ten komunikat, to korzystasz z Opery, Firefoxa albo Chroma, które uniemożliwiają zamykanie okien poprzez skrypt js. Mogliby wziąć przykład z Edge i wyświetlić komunikat, który blokuje/zezwala na akcję zamknięcia karty. Dane zostały wyczyszczone.
    </p>

    @Html.ActionLink("Kliknij tutaj, żeby wrócić do strony początkowej.", "Index", new { area = "", controller = "Home" })

ToDo/ToDo/Areas/Zadania/Views/Zadanie/Index.cshtml
@model ToDo.Areas.Zadania.ViewModel.TasksViewConfigModel

@using ToDo.Areas.Zadania.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var availableSite = Model.ViewConfig.MultiplierTaskPerSite != 0
        ? Math.Ceiling((decimal)(Model.SortList.CountAllTasks) / Model.ViewConfig.TaskPerSite)
        : 1;
    if (Model.SortList != null)
    {
        if (Model.SortList.actualList.Count() > 0)
        {
            var test = Model.ViewConfig.DescriptionTaskId;
        }
    }
    var descriptionModel = (Model.SortList != null && Model.SortList.actualList.Count() > 0)
        ? Model.SortList.actualList.FirstOrDefault(t => t.Id == Model.ViewConfig.DescriptionTaskId)
        : null;

    var descriptionVisibleStyle = descriptionModel == null ? "none" : "inherit";

    var editedTask = Model.SortList != null
        ? Model.SortList.actualList.FirstOrDefault(t => t.Id == Model.ViewConfig.EditedTaskId)
        : null;
    var editedVisibleStyle = editedTask == null ? "none" : "inherit";

}

@{Html.RenderPartial("~/Areas/Zadania/Views/Shared/_PanelView.cshtml");}

@{ Html.RenderPartial("~/Areas/Zadania/Views/Shared/_SearchBar.cshtml", Model.SortList.SearchBar); }

@if (Model.ViewConfig.ActualViewType == ToDo.Services.Zadania.ViewType.LIST)
{
    Html.RenderPartial("~/Areas/Zadania/Views/Shared/_List.cshtml", Model);
    
}
else
{
    Html.RenderPartial("~/Areas/Zadania/Views/Shared/_Tail.cshtml", Model);
    
}

<div class="row">
    <div class="text-right">
        <p>
            Elementów na stronie
            <select class="btn" id="viewPerSite" onchange="ChangeElementsPerSite()">
                @for (var iterator = 1; iterator <= Model.ViewConfig.MaxMultiplierPerSite; iterator++)
                {
                    int value = iterator * Convert.ToInt32(Model.ViewConfig.BasePerSite);
                    if (value == Model.ViewConfig.TaskPerSite)
                    {
                        <option value="@iterator" selected="selected">@value</option>
                    }
                    else
                    {
                        <option value="@iterator">@value</option>
                    }
                }

            </select>
        </p>
    </div>
</div>

<div class="row">
    <div class="text-center">
        @if (Model.ViewConfig.ActualSite == 1)
        {
            <input type="button" value="Poprzedni" class="btn btn-primary" disabled />
        }
        else
        {
            <input type="button" value="Poprzedni" class="btn btn-primary" onclick="PreviousSite()" />
        }
        <select class="btn" id="actualSite" onchange="ChangeActualSite()">
            @for (var iterator = 1; iterator <= availableSite; iterator++)
            {
                if (iterator == Model.ViewConfig.ActualSite)
                {
                    <option value="@iterator" selected="selected">@iterator</option>
                }
                else
                {
                    <option value="@iterator">@iterator</option>
                }
            }
        </select>

        @if (Model.ViewConfig.ActualSite >= availableSite)
        {
            <input type="button" value="Następny" class="btn btn-primary" disabled />
        }
        else
        {
            <input type="button" value="Następny" class="btn btn-primary" onclick="NextSite()" />
        }
    </div>
</div>

<div id="popup" style="display: none;">
    <div id="AddPopUp">
        @{ Html.RenderPartial("~/Areas/Zadania/Views/Shared/_CreateTask.cshtml", new Task()); }
    </div>
    <div id="EditPopUp" style="display: @editedVisibleStyle">
        @if (editedTask != null)
        {
            Html.RenderPartial("~/Areas/Zadania/Views/Shared/_CreateTask.cshtml", editedTask);
        }
    </div>
    <div id="DescriptionPopUp" style="display: @descriptionVisibleStyle">
        @if (descriptionModel != null)
        {
            Html.RenderPartial("~/Areas/Zadania/Views/Shared/_DescriptionView.cshtml", descriptionModel);
        }
    </div>
    <div id="ExportPopUp" class="export-container">
        @{Html.RenderPartial("/Areas/Zadania/Views/Shared/_ExportView.cshtml");}
    </div>
</div>

<div id="Error" style="display: none;"></div>
<div id="DeleteModal" style="display: none;">Czy na pewno chcesz usunąć to zadanie?</div>

<script type="text/javascript">
    const ChangeActualSiteHelper = function (id) {
        location.href = `@Url.Action("ChangeActualSite", "Zadanie")/${id}`;
    }
    const ChangeActualSite = function () {
        const int = parseInt($('#actualSite').val());
        if (int == NaN)
            console.warn('Coś poszło nie tak. Wartość była tekstem.')
        else
            ChangeActualSiteHelper(int);
    }
    const PreviousSite = function () {
        const int = parseInt($('#actualSite').val()) - 1;
        if (int == NaN)
            console.warn('Coś poszło nie tak. Wartość była tekstem.')
        else
            ChangeActualSiteHelper(int);
    }
    const NextSite = function () {
        const int = parseInt($('#actualSite').val()) + 1;
        if (int == NaN)
            console.warn('Coś poszło nie tak. Wartość była tekstem.')
        else
            ChangeActualSiteHelper(int);

    }

    const ChangeElementsPerSite = function () {
        const value = $('#viewPerSite').val();

        location.href = `@Url.Action("ChangeTasksPerSite", "Zadanie")/${value}`;
    }

    const Select = function () {
        var selected = 0;
        var EditButton = $('#EditButton');

        $('.EditCheckboxes').each(function () {
            if ($(this).prop('checked'))
                selected++;
        });


        if (selected == 1)
            EditButton.removeClass('disabled').addClass('icon');
        else
            EditButton.removeClass('icon').addClass('disabled');
    }

    const Delete = function (id) {
        $('#DeleteModal').dialog({
            autoOpen: true,
            title: 'Potwierdzenie',
            modal: true,
            hide: 'clip',
            show: 'shake',
            buttons: [
                {
                    text: "OK",
                    click: function () {
                        @{
                            <text>
                        location.href = `@Url.Action("Delete", "Zadanie")/${id}`;
                            </text>
                        }
                    }
                },
                {
                    text: "Anuluj",
                    click: function () {
                        $(this).dialog('close');
                    }
                }]
        });
    }

    @{
        <text>
    const LoadModalWindow = function () {
        Select();
        PopUp.OpenDialog('@Model.ViewConfig.VisibleModal');
    };

    if (window.addEventListener) {
        window.addEventListener('load', LoadModalWindow, false);
    }
    else if (window.attachEvent) {
        window.attachEvent('onload', LoadModalWindow);
    }

        </text>
    }
</script>

@if (Model.Exception != String.Empty && Model.Exception != null)
{
    Html.RenderPartial("~/Areas/Zadania/Views/Shared/_ExceptionHandle.cshtml", Model.Exception);
}