ToDo/ToDo/Areas/ToDo/Models/Export/ExportPdf.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ToDo.Areas.ToDo.Models.Tasks;
using System.IO;
using System.Web.UI;
using System.Web.Helpers;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.Web.Mvc;

namespace ToDo.Areas.ToDo.Models.Export
{
    public class ExportPdf : Exporter
    {
        private IEnumerable<Task> _list;

        public ExportPdf(HttpResponseBase response) : base(response) { }

        protected override void Prepare(bool actualSite)
        {
            _list = MyList(actualSite);
        }

        public override void Export()
        {
            WebGrid grid = new WebGrid(source: _list, canPage: false, canSort: false);
            string gridHtml = grid.GetHtml(
                   columns: grid.Columns(
                            grid.Column("Action", "Czynność"),
                            grid.Column("Topic", "Temat"),
                            grid.Column("Start", "Data rozpoczęcia"),
                            grid.Column("End", "Data zakończenia"),
                            grid.Column("ActualStatus", "Status"),
                            grid.Column("ActualPriority", "Priorytet"),
                            grid.Column("Progress", "%")
                           )
                    ).ToString();
            string exportData = String.Format("{0}{1}", "", gridHtml);
            var bytes = System.Text.Encoding.UTF8.GetBytes(exportData);
            using (var input = new MemoryStream(bytes)) {
                var output = new MemoryStream();
                Document document = new Document(PageSize.A4, 50, 50, 50, 50);
                var writer = PdfWriter.GetInstance(document, output);
                writer.CloseStream = false;
                document.Open();
                var xmlWorker = iTextSharp.tool.xml.XMLWorkerHelper.GetInstance();
                xmlWorker.ParseXHtml(writer, document, input, System.Text.Encoding.UTF8);
                document.Close();
                output.Position = 0;
                _memory = output;
            }
        }

        public override string ContentType { get; } = "application/pdf";
        public override string Extension { get; } = "pdf";
    }
}

ToDo/ToDo/Areas/ToDo/Models/Export/ExportTXT.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ToDo.Areas.ToDo.Models.Tasks;

namespace ToDo.Areas.ToDo.Models.Export
{
    public class ExportTxt : Exporter
    {
        public ExportTxt(HttpResponseBase response) : base(response) {}

        protected override void Prepare(bool actualSite)
        {
            IEnumerable<Task> list = MyList(actualSite);

            StringBuilder sb = new StringBuilder();

            sb.AppendLine($"Czynność\tTemat\tData rozpoczęcia\tData zakończenia\tStatus\tPriorytet\t% zakończenia;");

            foreach (Task t in list)
                sb.AppendLine($"{t.Action}\t{t.Topic}\t{t.Start}\t{t.End}\t{t.ActualStatus}\t{t.ActualPriority}\t{t.Progress};");

            _result = sb.ToString();
        }

        public override string ContentType { get; } = "text/plain";
        public override string Extension { get; } = "txt";

    }
}

ToDo/ToDo/Areas/ToDo/Models/Export/ExportXls.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using ToDo.Areas.ToDo.Models.Tasks;

namespace ToDo.Areas.ToDo.Models.Export
{
    public class ExportXls : Exporter
    {
        public ExportXls(HttpResponseBase response) : base(response) { }

        protected override void Prepare(bool actualSite)
        {
            IEnumerable<Task> list = MyList(actualSite);

            StringBuilder sb = new StringBuilder();

            sb.AppendLine($"\"Czynność\",\"Temat\",\"Data rozpoczęcia\",\"Data zakończenia\",\"Status\",\"Priorytet\",\"% zakończenia\"");

            foreach (Task t in list)
                sb.AppendLine($"{t.Action},\"{t.Topic}\",{t.Start},{t.End},{t.ActualStatus},{t.ActualPriority},{t.Progress}");

            _result = sb.ToString();
        }

        public override string ContentType { get; } = "text/xls";
        public override string Extension { get; } = "xls";
    }
}

ToDo/ToDo/Areas/ToDo/Models/Export/Exporter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ToDo.Areas.ToDo.Models.View;
using ToDo.Areas.ToDo.Models.Tasks;
using System.Web.Mvc;
using System.IO;

namespace ToDo.Areas.ToDo.Models.Export
{
    public abstract class Exporter : IExport
    {
        protected HttpResponseBase _response;
        protected string _result;
        protected byte[] _resultByte;
        protected Config _viewConfig;
        protected IListOfTasks _tasks;
        public MemoryStream _memory { get; protected set; }

        public Exporter(HttpResponseBase response)
        {
            _response = response;
            _result = "";
            _viewConfig = Config.GetInstance();
            _tasks = ListOfTasks.GetInstance();
        }


        bool IExport.PrepareData(bool actualSite)
        {
            bool result = true;
            
            Prepare(actualSite);

            return result;
        }

        public virtual void Export()
        {
            _response.Clear();
            _response.ClearHeaders();

            _response.AppendHeader("Content-Length", (this as IExport).Length.ToString());
            _response.ContentType = (this as IExport).ContentType;
            _response.AppendHeader("Content-Disposition", $"attachment;filename=\"{GetName}.{(this as IExport).Extension}\"");

            _response.ContentType = (this as IExport).ContentType;
            _response.Write(_result);

            _response.End();
            _response.Close();
    }
        

        int IExport.Length {
            get {
                return _result.Length;
            }
        }

        protected IEnumerable<Task> MyList(bool actualSite)
        {
            return actualSite
                ? _tasks.GetTasks(_viewConfig.SkipPages(), _viewConfig.ActualPerSite)
                : _tasks.GetTasks();
        }

        protected abstract void Prepare(bool actualSite);

        public abstract string ContentType { get; }
        public abstract string Extension { get; }
        public string GetName { get { return "TasksList"; } }
    }
}

ToDo/ToDo/Areas/ToDo/Models/Export/IEXport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ToDo.Areas.ToDo.Models.Export
{
    public interface IExport
    {
        /// <summary>
        /// Zwraca nazwę pliku.
        /// </summary>
        string GetName { get; }

        /// <summary>
        /// Ustawienia content-type dla pliku.
        /// </summary>
        string ContentType { get; }

        /// <summary>
        /// Zwraca długość pliku eksportowanego.
        /// </summary>
        /// <returns>Długość pliku.</returns>
        int Length { get; }

        /// <summary>
        /// Rozszerzenie pliku.
        /// </summary>
        string Extension { get; }

        /// <summary>
        /// Funkcja przygotowująca dane do eksportu.
        /// </summary>
        /// <param name="actualSite">Jeśli wynosi "on", to pobierze tylko aktualną stronę/</param>
        /// <returns>Prawdę dla poprawnego przygotowania danych.</returns>
        bool PrepareData(bool actualSite);

        /// <summary>
        /// Eksportuje dane.
        /// </summary>
        /// <returns>Zwraca plik w formacie string.</returns>
        void Export();
    }
}

ToDo/ToDo/Areas/ToDo/Controllers/ToDoController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ToDo.Areas.ToDo.Models.Export;
using ToDo.Areas.ToDo.Models.Tasks;
using ToDo.Areas.ToDo.Models.View;

namespace ToDo.Areas.ToDo.Controllers
{
    public class ToDoController : Controller {
        IListOfTasks Tasks = ListOfTasks.GetInstance();
        Config ViewConfig = Config.GetInstance();
        static Task editTask;
        
        static int tmpTest = 1;
        // GET: ToDo/ToDo
        public ActionResult Index()
        {
            PrepareViewData();

            return View();
        }


        [HttpPost]
        public ActionResult Export(string ExportType, string OneSite)
        {

            if (Request.HttpMethod == "POST") {
                Dictionary<string, IExport> exporters = new Dictionary<string, IExport> {
                    { "TXT", new ExportTxt(Response) },
                    { "XLS", new ExportXls(Response) },
                    { "PDF", new ExportPdf(Response) }
                };

                IExport exporter = exporters[ExportType];

                bool onlyOneSite;
                try {
                    onlyOneSite = OneSite.Equals("on");
                } catch (NullReferenceException) {
                    onlyOneSite = false;
                }

                exporter.PrepareData( onlyOneSite );

                exporter.Export();

                if (ExportType.Equals("PDF")) 
                    return File((exporter as ExportPdf)._memory, exporter.ContentType, $"{exporter.GetName}.{exporter.Extension}");
            }

            PrepareViewData();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Sort(string sortType)
        {

            if (Request.HttpMethod == "POST") {
                AvailableSort selectedSort = (AvailableSort)Enum.Parse(typeof(AvailableSort), sortType);
                Tasks.SelectedSort = selectedSort;
                Tasks.OrderNow();
            }
            PrepareViewData();

            return RedirectToAction("Index");
        }
        // GET: ToDo/ToDo/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        // GET: ToDo/ToDo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection) {
            if (Request.HttpMethod == "POST") {
                string action = Request.Form["Action"];
                string topic = Request.Form["Topic"];
                string start = Request.Form["Start"];
                string end = Request.Form["End"];
                string status = Request.Form["ActualStatus"];
                string priority = Request.Form["ActualPriority"];
                string progress = Request.Form["Progress"];
                string desc = Request.Form["Desc"];
                string file = Request.Form["File"];

                Task tmp = new Task {
                    Topic = topic,
                    Action = action,
                    Start = Convert.ToDateTime(start),
                    End = Convert.ToDateTime(end),
                    ActualStatus = Convert.ToInt32(status),
                    ActualPriority = Convert.ToInt32(priority),
                    Progress = Convert.ToInt32(progress),
                    Description = desc
                };
                Tasks.Add(tmp);

                tmpTest++;
                return RedirectToAction("Index");
                
            } else {

                PrepareViewData();

                return View("Index");
            }
        }
        
        [HttpPost]
        public JsonResult SetEdit(string element)
        {
            editTask = Tasks.Get(Convert.ToInt32(element));
            PrepareViewData();

            return Json("OK open Edit");
        }

        [HttpPost]
        public JsonResult Description(string element)
        {
            editTask = Tasks.Get(Convert.ToInt32(element));
            PrepareViewData();

            return Json("OK open Description");
        }

        // POST: ToDo/ToDo/Edit/5
        [HttpPost]
        public ActionResult Edit(FormCollection collection) {
            try
            {
                int ID = editTask.ID;
                string action = Request.Form["Action"];
                string topic = Request.Form["Topic"];
                string start = Request.Form["Start"];
                string end = Request.Form["End"];
                string status = Request.Form["ActualStatus"];
                string priority = Request.Form["ActualPriority"];
                string progress = Request.Form["Progress"];
                string desc = Request.Form["Desc"];
                string file = Request.Form["File"];

                Task tmp = new Task {
                    ID = ID, 
                    Topic = topic,
                    Action = action,
                    Start = Convert.ToDateTime(start),
                    End = Convert.ToDateTime(end),
                    ActualStatus = Convert.ToInt32(status),
                    ActualPriority = Convert.ToInt32(priority),
                    Progress = Convert.ToInt32(progress),
                    Description = desc
                };

                Tasks.Edit(ID, tmp);


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        [HttpPost]
        public JsonResult Delete(string element) {
            int selectedId = Convert.ToInt32(element);

            Tasks.Remove(selectedId);
            PrepareViewData();
            
            return Json( "OK" );
        }

        public ActionResult Exit() {
            Tasks.Clear();
            return View("Exit");
        }

        [NonAction]
        public void PrepareViewData()
        {
            ViewData["Tasks"] = GetOrderedList();
            ViewData["ViewConfig"] = ViewConfig;
            ViewData["AvailableSites"] =
                Convert.ToInt32(
                    Math.Floor(
                        Convert.ToDecimal(
                            (Tasks.AllElements() - 1) / ViewConfig.ActualPerSite
                            )
                        )
                    );
            ViewData["ReverseSort"] = Tasks.ReverseSort;
            ViewData["ActualSort"] = Tasks.SelectedSort;
            ViewData["CountOfTasks"] = Tasks.AllElements();
            ViewData["EditTask"] = editTask;
        }

        [NonAction] 
        public IEnumerable<Task> GetOrderedList() {
            return Tasks.GetTasks(ViewConfig.SkipPages(), ViewConfig.ActualPerSite);
        }

        [HttpPost]
        public JsonResult ElementsPerSite(string element)
        {
            ViewConfig.ActualPerSite = Convert.ToInt32(element);

            return Json("OK");
        }

        [HttpPost]
        public JsonResult ActualSite(string element)
        {
            ViewConfig.ActualSite = Convert.ToInt32(element);

            return Json("OK");
        }

        [HttpPost]
        public JsonResult NextInList(string element)
        {
            int actualId = Convert.ToInt32(element);
            Tasks.SwapNext(actualId);

            return Json( "OK" );
        }
        [HttpPost]
        public JsonResult PreviousInList(string element)
        {
            int actualId = Convert.ToInt32(element);
            Tasks.SwapPrevious(actualId);

            return Json("OK");
        }
    }
}

ToDo/ToDo/Areas/ToDo/Views/Shared/_DescriptionView.cshtml
@model ToDo.Areas.ToDo.Models.Tasks.Task

<div>
    <h4>Zadanie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Action)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Topic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActualPriority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActualPriority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Progress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Progress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilePath)
        </dd>

    </dl>
</div>

ToDo/ToDo/Areas/ToDo/Views/Shared/_ExportView.cshtml
@using (Html.BeginForm("Export", "ToDo", FormMethod.Post)) {
    <div class="row text-center">
        <button type="submit" value="PDF" name="ExportType"><i class="fas fa-file-pdf icon-export text-primary"></i></button>
    </div>
    <div class="row text-center">
        <button type="submit" value="XLS" name="ExportType"><i class="fas fa-file-excel icon-export text-primary"></i></button>
    </div>
    <div class="row text-center">
        <button type="submit" value="TXT" name="ExportType"><i class="fas fa-file-alt icon-export text-primary"></i></button>
    </div>
    <div class="row">
        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-2 form-check">
            <label class="switch">
                <input type="checkbox" id="OneSite" onclick="SelectOneSiteOrAll()" name="OneSite">
                <span class="slider round"></span>
            </label>
        </div>

    </div>
    <div class="row text-center" id="export-site">
        Wszystkie strony
    </div>
}

ToDo/ToDo/Areas/ToDo/Views/Shared/_ListingView.cshtml
@{
    ToDo.Areas.ToDo.Models.Tasks.Task modelForNames = null;

    IEnumerable<ToDo.Areas.ToDo.Models.Tasks.Task> myModel = this.ViewData["tasks"] as IEnumerable<ToDo.Areas.ToDo.Models.Tasks.Task>;

    string myType = this.ViewData.ContainsKey("Type") ? this.ViewData["Type"].ToString() : "NIE MA?";
}

@if (myType == "list") {
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => modelForNames.Action)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.Topic)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.Start)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.End)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.ActualStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.ActualPriority)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.Progress)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => modelForNames.FilePath)
            </th>
            <th></th>
        </tr>

        @foreach (var item in myModel) {
            <tr>
                <td style="font-weight: bold">
                    @Html.DisplayFor(modelItem => item.Action)
                </td>
                <td style="font-weight: bold">
                    @Html.DisplayFor(modelItem => item.Topic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Start)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.End)
                </td>
                <td style="background-color: yellow">
                    @Html.DisplayFor(modelItem => item.ActualStatus)
                </td>
                <td style="background-color: lightblue">
                    @Html.DisplayFor(modelItem => item.ActualPriority)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Progress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FilePath)
                </td>
            </tr>
        }

    </table>
}

@if (myType == "tile") {

    <div class="row">

        @foreach (var tile in myModel) {
            <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-lg-3 col-md-3 col-sm-3 col-xs-3" style="border: 2px solid black; border-radius: 2px">
                <div class="row">
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 text-center" style="background-color: lightblue">
                        @Html.DisplayFor(modelItem => tile.ActualPriority)
                    </div>
                    <div class="col-lg-offset-7 col-md-offset-7 col-sm-offset-7 col-xs-offset-7 col-lg-2 col-md-2 col-sm-2 col-xs-2 text-center"style="background-color: yellow">

                        @Html.DisplayFor(modelItem => tile.ActualStatus)
                    </div>
                </div>
                <div class="row text-center" style="font-weight: bold">
                    @Html.DisplayFor(modelItem => tile.Action)
                </div>
                <div class="row text-center" style="font-weight: bold">
                    @Html.DisplayFor(modelItem => tile.Topic)
                </div>
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                        @Html.DisplayFor(modelItem => tile.Start) - @Html.DisplayFor(modelItem => tile.End)
                    </div>
                    <div class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 col-lg-2 col-md-2 col-sm-2 col-xs-2">
                        @Html.DisplayFor(modelItem => tile.Progress)
                    </div>

                </div>
            </div>
        }
    </div>
    
}

ToDo/ToDo/Areas/ToDo/Views/Shared/_PanelView.cshtml
<div class="row">
    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12 panel tasks">
        <div class="row">
            <div class="col-lg-offset-1 col-lg-2 col-md-offset-1 col-md-2 col-sm-offset-1 col-sm-2 col-xs-offset-1 col-xs-2 text-center">
                <p class="icon-cont" onclick="OpenModalWindow('Add')">
                    <i class="fas fa-plus icon text-success"></i>
                </p>
            </div>
            <div class="col-lg-offset-2 col-lg-2 col-md-offset-2 col-md-2 col-sm-offset-2 col-sm-2 col-xs-offset-2 col-xs-2">
                <p class="icon-cont"  onclick="OpenModalWindow('Edit')">
                    <i id="EditButton" class="fas fa-edit text-primary disabled"></i>
                </p>
            </div>
            <div class="col-lg-offset-2 col-lg-2 col-md-offset-2 col-md-2 col-sm-offset-2 col-sm-2 col-xs-offset-2 col-xs-2">
                <p class="icon-cont" onclick="OpenModalWindow('Export')" id="export_btn">
                    <i class="fas fa-file-export icon text-primary"></i>
                </p>
            </div>
        </div>
    </div>
    <div class="col-lg-offset-2 col-lg-5 col-md-offset-2 col-md-5 col-sm-6 col-xs-12 panel app">
        <div class="col-lg-offset-1 col-lg-2 col-md-offset-1 col-md-2 col-sm-offset-1 col-sm-2 col-xs-offset-1 col-xs-2">
            <p class="icon-cont"  onclick="OpenModalWindow('List')">
                <i class="fas fa-list icon text-primary"></i>
            </p>
        </div>
        <div class="col-lg-offset-2 col-lg-2 col-md-offset-2 col-md-2 col-sm-offset-2 col-sm-2 col-xs-offset-2 col-xs-2">
            <p class="icon-cont"  onclick="OpenModalWindow('Tile')">
                <i class="fas fa-th-large icon text-primary"></i>
            </p>
        </div>
        <div class="col-lg-offset-2 col-lg-2 col-md-offset-2 col-md-2 col-sm-offset-2 col-sm-2 col-xs-offset-2 col-xs-2">
            <p class="icon-cont">
                <a href="@Url.Action("Exit")" class="link-with-icon">
                    <i class="fas fa-window-close icon text-danger"></i>
                </a>
            </p>
        </div>
    </div>
</div>